# Generated by Django 2.1.7 on 2019-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_auto_20190228_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='FirstName',
            field=models.TextField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='LastName',
            field=models.TextField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='MiddleName',
            field=models.TextField(max_length=50, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='email address'),
        ),
    ]
