# Generated by Django 2.1.7 on 2019-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_auto_20190228_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='FirstName',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='LastName',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='MiddleName',
            field=models.CharField(max_length=50, null=True, verbose_name='Middle name'),
        ),
    ]
