# Generated by Django 2.1.7 on 2019-02-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0006_auto_20190228_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('MiddleName', models.CharField(blank=True, max_length=30, null=True)),
                ('LastName', models.CharField(max_length=30)),
                ('FatherName', models.CharField(max_length=150)),
                ('Branch', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=150)),
                ('Date_of_Birth', models.DateField()),
            ],
        ),
    ]
