# Generated by Django 2.1.7 on 2019-03-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0007_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'batche'},
        ),
        migrations.AddField(
            model_name='student',
            name='User_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customauth.Batch'),
            preserve_default=False,
        ),
    ]
