# Generated by Django 2.1.7 on 2019-03-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0008_auto_20190301_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='User_Id',
            new_name='Batch',
        ),
    ]
