# Generated by Django 2.1.7 on 2019-03-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0009_auto_20190301_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='User_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
