# Generated by Django 2.1.7 on 2019-03-01 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0010_student_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('MiddleName', models.CharField(blank=True, max_length=30, null=True)),
                ('LastName', models.CharField(max_length=30)),
                ('Date_of_Birth', models.DateField()),
                ('FacultyType', models.CharField(max_length=30)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
